// <auto-generated />
using System;
using E_Commerce_BackEnd.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce_BackEnd.Migrations.V1
{
    [DbContext(typeof(ECommerceContext))]
    partial class ECommerceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce_BackEnd.Models.OrderRelatedModels.Comenzi", b =>
                {
                    b.Property<int>("IdComanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_comanda");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdComanda"));

                    b.Property<DateTime>("DataEmitereComanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("data_emitere_comanda")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IdDetaliu")
                        .HasColumnType("integer")
                        .HasColumnName("id_detaliu");

                    b.Property<string>("StatusComanda")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status_comanda");

                    b.Property<string>("TipPlata")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tip_plata");

                    b.HasKey("IdComanda");

                    b.HasIndex("IdDetaliu");

                    b.ToTable("comenzi", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.OrderRelatedModels.Locatii", b =>
                {
                    b.Property<int>("IdLocatie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_locatie");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLocatie"));

                    b.Property<string>("CodPostal")
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("cod_postal");

                    b.Property<string>("Judet")
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("judet");

                    b.Property<string>("Oras")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("oras");

                    b.HasKey("IdLocatie");

                    b.ToTable("locatii", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.OrderRelatedModels.ProduseCuComenzi", b =>
                {
                    b.Property<int>("IdProduseCuComenzi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_produse_cu_comenzi");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProduseCuComenzi"));

                    b.Property<int?>("CuloriIdCuloare")
                        .HasColumnType("integer");

                    b.Property<int>("IdComanda")
                        .HasColumnType("integer")
                        .HasColumnName("id_comanda");

                    b.Property<int>("IdCuloare")
                        .HasColumnType("integer")
                        .HasColumnName("id_culoare");

                    b.Property<int>("IdDimensiune")
                        .HasColumnType("integer")
                        .HasColumnName("id_dimensiune");

                    b.Property<int?>("IdManopera")
                        .HasColumnType("integer")
                        .HasColumnName("id_manopera");

                    b.Property<int>("IdProdus")
                        .HasColumnType("integer")
                        .HasColumnName("id_produs");

                    b.Property<int>("NrBucati")
                        .HasColumnType("integer")
                        .HasColumnName("nr_buc");

                    b.HasKey("IdProduseCuComenzi");

                    b.HasIndex("CuloriIdCuloare");

                    b.HasIndex("IdComanda");

                    b.HasIndex("IdProdus");

                    b.ToTable("produse_cu_comenzi", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.AsociereSeturi", b =>
                {
                    b.Property<int>("IdAsociereSet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_asociere_set");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAsociereSet"));

                    b.Property<int>("IdProdus")
                        .HasColumnType("integer")
                        .HasColumnName("id_produs");

                    b.Property<int>("IdSet")
                        .HasColumnType("integer")
                        .HasColumnName("id_set");

                    b.HasKey("IdAsociereSet");

                    b.HasIndex("IdProdus");

                    b.HasIndex("IdSet");

                    b.ToTable("asociere_seturi", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.CodCulori", b =>
                {
                    b.Property<int>("IdCodCuloare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cod_culoare");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCodCuloare"));

                    b.Property<string>("CodCuloare")
                        .HasMaxLength(5)
                        .HasColumnType("varchar")
                        .HasColumnName("cod_culoare");

                    b.HasKey("IdCodCuloare");

                    b.ToTable("cod_culori", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Culori", b =>
                {
                    b.Property<int>("IdCuloare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_culoare");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCuloare"));

                    b.Property<int>("IdCodCuloare")
                        .HasColumnType("integer")
                        .HasColumnName("id_cod_culoare");

                    b.Property<string>("NumeCuloare")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_culoare");

                    b.HasKey("IdCuloare");

                    b.HasIndex("IdCodCuloare");

                    b.ToTable("culori", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Dimensiuni", b =>
                {
                    b.Property<int>("IdDimensiune")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_dimensiune");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDimensiune"));

                    b.Property<string>("Latime")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar")
                        .HasColumnName("latime");

                    b.Property<string>("Lungime")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar")
                        .HasColumnName("lungime");

                    b.Property<bool?>("PerdeaEstePereche")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RecomandarePat")
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("recomandare_pat");

                    b.HasKey("IdDimensiune");

                    b.ToTable("dimensiuni", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Imagini", b =>
                {
                    b.Property<int>("IdImagine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_imagine");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdImagine"));

                    b.Property<string>("CaleImagine")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("cale_imagine");

                    b.Property<int>("IdProdusCuCuloare")
                        .HasColumnType("integer")
                        .HasColumnName("id_produs_culoare");

                    b.HasKey("IdImagine");

                    b.HasIndex("IdProdusCuCuloare");

                    b.ToTable("imagini", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.InelePrindere", b =>
                {
                    b.Property<int>("IdInel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_inel_prindere");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdInel"));

                    b.Property<string>("CuloareInel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("culoare_inel");

                    b.Property<decimal>("PretPerMetruInele")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("pret_metru_inele");

                    b.HasKey("IdInel");

                    b.ToTable("inele_prindere", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Manopere", b =>
                {
                    b.Property<int>("IdManopera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_manopera");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdManopera"));

                    b.Property<int?>("IdInelPrindere")
                        .HasColumnType("integer")
                        .HasColumnName("id_inel_prindere");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("integer")
                        .HasColumnName("id_material");

                    b.Property<int>("IdTipGalerie")
                        .HasColumnType("integer")
                        .HasColumnName("id_tip_galerie");

                    b.Property<int>("IdTipLinie")
                        .HasColumnType("integer")
                        .HasColumnName("id_tip_linie");

                    b.HasKey("IdManopera");

                    b.HasIndex("IdInelPrindere");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdTipGalerie");

                    b.HasIndex("IdTipLinie");

                    b.ToTable("manopere", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Materiale", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_material");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMaterial"));

                    b.Property<string>("NumeMaterial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_material");

                    b.Property<decimal>("PretMaterial")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("pret_metru_material");

                    b.HasKey("IdMaterial");

                    b.ToTable("materiale", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Producatori", b =>
                {
                    b.Property<int>("IdProducator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_producator");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProducator"));

                    b.Property<string>("NumeProducator")
                        .HasMaxLength(5)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_producator");

                    b.HasKey("IdProducator");

                    b.ToTable("producatori", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", b =>
                {
                    b.Property<int>("IdProdus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_produs");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProdus"));

                    b.Property<sbyte>("ActivInMagazin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("activ_in_magazin");

                    b.Property<string>("CodProdus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar")
                        .HasColumnName("cod_produs");

                    b.Property<string>("Compozitie")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("compozitie");

                    b.Property<string>("Descriere")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("descriere");

                    b.Property<sbyte?>("FataReversibila")
                        .HasColumnType("tinyint")
                        .HasColumnName("fata_reversbila");

                    b.Property<decimal>("Greutate")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("greutate");

                    b.Property<int?>("IdProducator")
                        .HasColumnType("integer")
                        .HasColumnName("id_producator");

                    b.Property<string>("Ingrijire")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ingrijire");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("isDeleted");

                    b.Property<string>("NumeProdus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_produs");

                    b.Property<ushort?>("Stoc")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("stoc");

                    b.Property<byte>("Tva")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("TVA");

                    b.HasKey("IdProdus");

                    b.HasIndex("CodProdus")
                        .IsUnique()
                        .HasDatabaseName("Index_CodProdus");

                    b.HasIndex("IdProducator");

                    b.ToTable("produse", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.ProduseCuCulori", b =>
                {
                    b.Property<int>("IdProdusCuCuloare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_produs_culoare");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProdusCuCuloare"));

                    b.Property<int?>("IdCuloare")
                        .HasColumnType("integer")
                        .HasColumnName("id_culoare");

                    b.Property<int>("IdProdus")
                        .HasColumnType("integer")
                        .HasColumnName("id_produs");

                    b.HasKey("IdProdusCuCuloare");

                    b.HasIndex("IdCuloare");

                    b.HasIndex("IdProdus");

                    b.ToTable("culori_produse", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.ProduseCuDimensiuni", b =>
                {
                    b.Property<int>("IdProdusCuDimensiune")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_produs_cu_dimensiune");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProdusCuDimensiune"));

                    b.Property<int?>("IdDimensiune")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("id_dimensiune");

                    b.Property<int>("IdProdus")
                        .HasColumnType("integer")
                        .HasColumnName("id_produs");

                    b.Property<decimal>("Pret")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("pret");

                    b.HasKey("IdProdusCuDimensiune");

                    b.HasIndex("IdDimensiune");

                    b.HasIndex("IdProdus");

                    b.ToTable("dimensiuni_produse", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Seturi", b =>
                {
                    b.Property<int>("IdSet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_set");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSet"));

                    b.Property<string>("DescriereSet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("descriere_set");

                    b.Property<string>("NumeSet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_set");

                    b.HasKey("IdSet");

                    b.ToTable("seturi", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriGalerie", b =>
                {
                    b.Property<int>("IdTipGalerie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tip_galerie");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipGalerie"));

                    b.Property<string>("NumeTipGalerie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_galerie");

                    b.Property<decimal>("PretTipGalerie")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("pret_metru_galerie");

                    b.HasKey("IdTipGalerie");

                    b.ToTable("tipuri_galerie", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriLinie", b =>
                {
                    b.Property<int>("IdTipLinie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tip_linie");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipLinie"));

                    b.Property<string>("NumeTipLinie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_tip_linie");

                    b.Property<decimal>("PretPeTipLinie")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("pret_metru_linie");

                    b.HasKey("IdTipLinie");

                    b.ToTable("tipuri_linie", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriPeProduse", b =>
                {
                    b.Property<int>("IdTipPeProdus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tip_pe_produs");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipPeProdus"));

                    b.Property<int>("IdProdus")
                        .HasColumnType("integer")
                        .HasColumnName("id_produs");

                    b.Property<int>("IdTipProdus")
                        .HasColumnType("integer")
                        .HasColumnName("id_tip_produs");

                    b.HasKey("IdTipPeProdus");

                    b.HasIndex("IdProdus");

                    b.HasIndex("IdTipProdus");

                    b.ToTable("tipuri_pe_produse", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriProduse", b =>
                {
                    b.Property<int>("IdTipProdus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tip_pe_produs");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipProdus"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar")
                        .HasColumnName("categorie");

                    b.Property<string>("TipProdus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("tip_produs");

                    b.HasKey("IdTipProdus");

                    b.ToTable("tipuri_produse", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductVouchersModels.ProduseCuVouchere", b =>
                {
                    b.Property<int>("IdProdusCuVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_produs_cu_voucher");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProdusCuVoucher"));

                    b.Property<int>("IdProdus")
                        .HasColumnType("integer")
                        .HasColumnName("id_produs");

                    b.Property<int?>("IdVoucher")
                        .HasColumnType("integer")
                        .HasColumnName("id_voucher");

                    b.HasKey("IdProdusCuVoucher");

                    b.HasIndex("IdProdus");

                    b.HasIndex("IdVoucher");

                    b.ToTable("produse_cu_vouchere", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductVouchersModels.Vouchere", b =>
                {
                    b.Property<int>("IdVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_voucher");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVoucher"));

                    b.Property<string>("CodVoucher")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("cod_voucher");

                    b.Property<decimal>("Reducere")
                        .HasPrecision(2, 2)
                        .HasColumnType("decimal(2,2)")
                        .HasColumnName("reducere");

                    b.HasKey("IdVoucher");

                    b.ToTable("vouchere", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.Adrese", b =>
                {
                    b.Property<int>("IdAdresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_adresa");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAdresa"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("alias");

                    b.Property<string>("Bloc")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("bloc");

                    b.Property<int>("IdCont")
                        .HasColumnType("integer")
                        .HasColumnName("id_cont");

                    b.Property<int>("IdLocatie")
                        .HasColumnType("integer")
                        .HasColumnName("id_locatie");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("isDeleted");

                    b.Property<string>("NrBloc")
                        .HasMaxLength(7)
                        .HasColumnType("varchar")
                        .HasColumnName("nr_bloc");

                    b.Property<string>("NrStrada")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar")
                        .HasColumnName("nr_strada");

                    b.Property<string>("Strada")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("strada");

                    b.Property<string>("TipAdresa")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tip_adresa");

                    b.HasKey("IdAdresa");

                    b.HasIndex("IdCont");

                    b.HasIndex("IdLocatie");

                    b.ToTable("adrese", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.Conturi", b =>
                {
                    b.Property<int>("IdCont")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cont");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCont"));

                    b.Property<string>("CodActivare")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("cod_activare");

                    b.Property<DateTime?>("DataCreare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("data_creare")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<sbyte?>("Gen")
                        .HasColumnType("tinyint")
                        .HasColumnName("gen");

                    b.Property<string>("NrTelefon")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("nr_telefon");

                    b.Property<string>("Nume")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("nume");

                    b.Property<DateTime>("OraLinkConfirmare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ora_link")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasColumnName("parola");

                    b.Property<string>("Prenume")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("prenume");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("username");

                    b.Property<sbyte>("Verificat")
                        .HasColumnType("tinyint")
                        .HasColumnName("verificat");

                    b.HasKey("IdCont");

                    b.ToTable("conturi", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.DetaliiFactura", b =>
                {
                    b.Property<int>("IdDetaliu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detaliu");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetaliu"));

                    b.Property<string>("Cif")
                        .HasMaxLength(12)
                        .HasColumnType("varchar")
                        .HasColumnName("CIF");

                    b.Property<int>("IdAdresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_adresa");

                    b.Property<string>("NumeFirma")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_firma");

                    b.HasKey("IdDetaliu");

                    b.HasIndex("IdAdresa");

                    b.ToTable("detalii_factura", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.OrderRelatedModels.Comenzi", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.UserRelatedModels.DetaliiFactura", "CDetaliiFactura")
                        .WithMany("DComenzi")
                        .HasForeignKey("IdDetaliu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DetaliiFactura");

                    b.Navigation("CDetaliiFactura");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.OrderRelatedModels.ProduseCuComenzi", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Culori", null)
                        .WithMany("CuloarePeComanda")
                        .HasForeignKey("CuloriIdCuloare");

                    b.HasOne("E_Commerce_BackEnd.Models.OrderRelatedModels.Comenzi", "Comanda")
                        .WithMany("PcComenzi")
                        .HasForeignKey("IdComanda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Comenzi_PC");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", "Produs")
                        .WithMany("ComenziProduse")
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Produse_PC");

                    b.Navigation("Comanda");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.AsociereSeturi", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", "Produs")
                        .WithMany("PAsociereSeturi")
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Produse_AS");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Seturi", "Set")
                        .WithMany("SAsociereSeturi")
                        .HasForeignKey("IdSet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Seturi_AS");

                    b.Navigation("Produs");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Culori", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.CodCulori", "CodCuloare")
                        .WithMany("CoduriCulori")
                        .HasForeignKey("IdCodCuloare")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CodCulori");

                    b.Navigation("CodCuloare");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Imagini", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.ProduseCuCulori", "ProdusCuCuloare")
                        .WithMany("ImagProduseCuCulori")
                        .HasForeignKey("IdProdusCuCuloare")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProduseCuCuloare_Imagini");

                    b.Navigation("ProdusCuCuloare");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Manopere", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.InelePrindere", "InelPrindereLaManopera")
                        .WithMany("InelPeManopere")
                        .HasForeignKey("IdInelPrindere")
                        .HasConstraintName("FK_Inele_Prindere");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Materiale", "MaterialLaManopere")
                        .WithMany("MaterialPeManopere")
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Materiale");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriGalerie", "TipGalerieLaManopera")
                        .WithMany("TipGalerieManopere")
                        .HasForeignKey("IdTipGalerie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tip_Galerie");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriLinie", "TipLinieLaManopera")
                        .WithMany("TipLiniePeManopere")
                        .HasForeignKey("IdTipLinie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tip_Linie");

                    b.Navigation("InelPrindereLaManopera");

                    b.Navigation("MaterialLaManopere");

                    b.Navigation("TipGalerieLaManopera");

                    b.Navigation("TipLinieLaManopera");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Producatori", "Producator")
                        .WithMany("ProducatoriProduse")
                        .HasForeignKey("IdProducator")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Producatori");

                    b.Navigation("Producator");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.ProduseCuCulori", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Culori", "Culoare")
                        .WithMany("CProduseCuCulori")
                        .HasForeignKey("IdCuloare")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Culori_ProduseCuCulori");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", "Produse")
                        .WithMany("PProduseCuCulori")
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Produse_ProduseCuCulori");

                    b.Navigation("Culoare");

                    b.Navigation("Produse");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.ProduseCuDimensiuni", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Dimensiuni", "PdDimensiune")
                        .WithMany("DProduseCuDimensiuni")
                        .HasForeignKey("IdDimensiune")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_Dimensiuni_PD");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", "PdProduse")
                        .WithMany("PProduseCuDimensiuni")
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Produse_PD");

                    b.Navigation("PdDimensiune");

                    b.Navigation("PdProduse");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriPeProduse", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", "TppProdus")
                        .WithMany("PTipuriPeProduse")
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Produse_TPP");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriProduse", "TppTipProdus")
                        .WithMany("TpTipuriPeProduse")
                        .HasForeignKey("IdTipProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TipProduse_TPP");

                    b.Navigation("TppProdus");

                    b.Navigation("TppTipProdus");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductVouchersModels.ProduseCuVouchere", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", "PvProdus")
                        .WithMany("PvProduse")
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Produse_PV");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductVouchersModels.Vouchere", "PvVoucher")
                        .WithMany("VProduse")
                        .HasForeignKey("IdVoucher")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Vouchere_PV");

                    b.Navigation("PvProdus");

                    b.Navigation("PvVoucher");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.Adrese", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.UserRelatedModels.Conturi", "Cont")
                        .WithMany("AdreseConturi")
                        .HasForeignKey("IdCont")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Conturi");

                    b.HasOne("E_Commerce_BackEnd.Models.OrderRelatedModels.Locatii", "Locatie")
                        .WithMany("AdreseLocatii")
                        .HasForeignKey("IdLocatie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Locatii");

                    b.Navigation("Cont");

                    b.Navigation("Locatie");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.DetaliiFactura", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.UserRelatedModels.Adrese", "Adrese")
                        .WithMany("DetaliiFacturi")
                        .HasForeignKey("IdAdresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Adrese");

                    b.Navigation("Adrese");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.OrderRelatedModels.Comenzi", b =>
                {
                    b.Navigation("PcComenzi");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.OrderRelatedModels.Locatii", b =>
                {
                    b.Navigation("AdreseLocatii");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.CodCulori", b =>
                {
                    b.Navigation("CoduriCulori");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Culori", b =>
                {
                    b.Navigation("CProduseCuCulori");

                    b.Navigation("CuloarePeComanda");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Dimensiuni", b =>
                {
                    b.Navigation("DProduseCuDimensiuni");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.InelePrindere", b =>
                {
                    b.Navigation("InelPeManopere");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Materiale", b =>
                {
                    b.Navigation("MaterialPeManopere");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Producatori", b =>
                {
                    b.Navigation("ProducatoriProduse");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", b =>
                {
                    b.Navigation("ComenziProduse");

                    b.Navigation("PAsociereSeturi");

                    b.Navigation("PProduseCuCulori");

                    b.Navigation("PProduseCuDimensiuni");

                    b.Navigation("PTipuriPeProduse");

                    b.Navigation("PvProduse");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.ProduseCuCulori", b =>
                {
                    b.Navigation("ImagProduseCuCulori");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Seturi", b =>
                {
                    b.Navigation("SAsociereSeturi");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriGalerie", b =>
                {
                    b.Navigation("TipGalerieManopere");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriLinie", b =>
                {
                    b.Navigation("TipLiniePeManopere");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriProduse", b =>
                {
                    b.Navigation("TpTipuriPeProduse");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductVouchersModels.Vouchere", b =>
                {
                    b.Navigation("VProduse");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.Adrese", b =>
                {
                    b.Navigation("DetaliiFacturi");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.Conturi", b =>
                {
                    b.Navigation("AdreseConturi");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.DetaliiFactura", b =>
                {
                    b.Navigation("DComenzi");
                });
#pragma warning restore 612, 618
        }
    }
}
