// <auto-generated />
using System;
using E_Commerce_BackEnd.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce_BackEnd.Migrations.V1_6
{
    [DbContext(typeof(ECommerceContext))]
    [Migration("20241128184124_CartUpdate")]
    partial class CartUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce_BackEnd.Models.OrderRelatedModels.Comenzi", b =>
                {
                    b.Property<int>("IdComanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_comanda");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdComanda"));

                    b.Property<string>("AwbComanda")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("awb_fan_courier");

                    b.Property<DateTime>("DataEmitereComanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("data_emitere_comanda")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IdAdresaFacturare")
                        .HasColumnType("integer")
                        .HasColumnName("id_adresa_facturare");

                    b.Property<int>("IdAdresaLivrare")
                        .HasColumnType("integer")
                        .HasColumnName("id_adresa_livrare");

                    b.Property<int?>("IdVoucher")
                        .HasColumnType("integer")
                        .HasColumnName("id_voucher");

                    b.Property<sbyte>("IsCancelable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1);

                    b.Property<string>("StatusComanda")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status_comanda");

                    b.Property<string>("TipPlata")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tip_plata");

                    b.HasKey("IdComanda");

                    b.HasIndex("IdAdresaFacturare");

                    b.HasIndex("IdAdresaLivrare");

                    b.HasIndex("IdVoucher");

                    b.ToTable("comenzi", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.OrderRelatedModels.Locatii", b =>
                {
                    b.Property<int>("IdLocatie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_locatie");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLocatie"));

                    b.Property<string>("CodPostal")
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("cod_postal");

                    b.Property<string>("Judet")
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("judet");

                    b.Property<string>("Oras")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("oras");

                    b.HasKey("IdLocatie");

                    b.ToTable("locatii", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.OrderRelatedModels.ProduseCuComenzi", b =>
                {
                    b.Property<int>("IdProduseCuComenzi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_produse_cu_comenzi");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProduseCuComenzi"));

                    b.Property<int>("IdComanda")
                        .HasColumnType("integer")
                        .HasColumnName("id_comanda");

                    b.Property<int>("IdCuloare")
                        .HasColumnType("integer")
                        .HasColumnName("id_culoare");

                    b.Property<int?>("IdDimensiune")
                        .HasColumnType("integer")
                        .HasColumnName("id_dimensiune");

                    b.Property<int?>("IdManopera")
                        .HasColumnType("integer")
                        .HasColumnName("id_manopera");

                    b.Property<int>("IdProdus")
                        .HasColumnType("integer")
                        .HasColumnName("id_produs");

                    b.Property<int?>("IdSet")
                        .HasColumnType("integer")
                        .HasColumnName("id_set");

                    b.Property<int>("NrBucati")
                        .HasColumnType("integer")
                        .HasColumnName("nr_buc");

                    b.Property<decimal>("PretCumparat")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("pret_baza");

                    b.HasKey("IdProduseCuComenzi");

                    b.HasIndex("IdComanda");

                    b.HasIndex("IdCuloare");

                    b.HasIndex("IdDimensiune");

                    b.HasIndex("IdManopera");

                    b.HasIndex("IdProdus");

                    b.HasIndex("IdSet");

                    b.ToTable("produse_cu_comenzi", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.AsociereSeturi", b =>
                {
                    b.Property<int>("IdAsociereSet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_asociere_set");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAsociereSet"));

                    b.Property<int?>("IdCuloare")
                        .HasColumnType("integer")
                        .HasColumnName("id_culoare");

                    b.Property<int?>("IdDimensiune")
                        .HasColumnType("integer")
                        .HasColumnName("id_dimensiune");

                    b.Property<int?>("IdManopera")
                        .HasColumnType("integer")
                        .HasColumnName("id_manopera");

                    b.Property<int>("IdProdus")
                        .HasColumnType("integer")
                        .HasColumnName("id_produs");

                    b.Property<int>("IdSet")
                        .HasColumnType("integer")
                        .HasColumnName("id_set");

                    b.HasKey("IdAsociereSet");

                    b.HasIndex("IdCuloare");

                    b.HasIndex("IdDimensiune");

                    b.HasIndex("IdManopera");

                    b.HasIndex("IdProdus");

                    b.HasIndex("IdSet");

                    b.ToTable("asociere_seturi", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.CodCulori", b =>
                {
                    b.Property<int>("IdCodCuloare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_cod_culoare");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCodCuloare"));

                    b.Property<string>("CodCuloare")
                        .HasMaxLength(5)
                        .HasColumnType("varchar")
                        .HasColumnName("cod_culoare");

                    b.HasKey("IdCodCuloare");

                    b.ToTable("cod_culori", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.CosCumparaturi", b =>
                {
                    b.Property<int>("IdProdusInCos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_produs_in_cos");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProdusInCos"));

                    b.Property<int>("CantitateProdus")
                        .HasColumnType("int")
                        .HasColumnName("cantitate_produs");

                    b.Property<int>("IdCont")
                        .HasColumnType("int")
                        .HasColumnName("id_cont");

                    b.Property<int>("IdCuloare")
                        .HasColumnType("int")
                        .HasColumnName("id_culoare");

                    b.Property<int?>("IdDimensiune")
                        .HasColumnType("int")
                        .HasColumnName("id_dimensiune");

                    b.Property<int?>("IdManopera")
                        .HasColumnType("int")
                        .HasColumnName("id_manopera");

                    b.Property<int?>("IdProdus")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("id_produs");

                    b.Property<int?>("IdSet")
                        .HasColumnType("int")
                        .HasColumnName("id_set");

                    b.Property<decimal>("PretProdus")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("pret_produs");

                    b.HasKey("IdProdusInCos");

                    b.HasIndex("IdCont");

                    b.HasIndex("IdCuloare");

                    b.HasIndex("IdDimensiune");

                    b.HasIndex("IdManopera");

                    b.HasIndex("IdProdus");

                    b.HasIndex("IdSet");

                    b.ToTable("cos_cumparaturi", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Culori", b =>
                {
                    b.Property<int>("IdCuloare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_culoare");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCuloare"));

                    b.Property<int>("IdCodCuloare")
                        .HasColumnType("integer")
                        .HasColumnName("id_cod_culoare");

                    b.Property<string>("NumeCuloare")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_culoare");

                    b.HasKey("IdCuloare");

                    b.HasIndex("IdCodCuloare");

                    b.ToTable("culori", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Dimensiuni", b =>
                {
                    b.Property<int>("IdDimensiune")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_dimensiune");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDimensiune"));

                    b.Property<string>("Latime")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar")
                        .HasColumnName("latime");

                    b.Property<string>("Lungime")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar")
                        .HasColumnName("lungime");

                    b.Property<bool?>("PerdeaEstePereche")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RecomandarePat")
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("recomandare_pat");

                    b.HasKey("IdDimensiune");

                    b.ToTable("dimensiuni", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Imagini", b =>
                {
                    b.Property<int>("IdImagine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_imagine");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdImagine"));

                    b.Property<string>("CaleImagine")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("cale_imagine");

                    b.Property<string>("FisierInBucket")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar")
                        .HasColumnName("bucket_directory");

                    b.Property<int>("IdProdusCuCuloare")
                        .HasColumnType("integer")
                        .HasColumnName("id_produs_culoare");

                    b.HasKey("IdImagine");

                    b.HasIndex("IdProdusCuCuloare");

                    b.ToTable("imagini", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.InelePrindere", b =>
                {
                    b.Property<int>("IdInel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_inel_prindere");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdInel"));

                    b.Property<string>("CaleRelativa")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("cale_relativa");

                    b.Property<string>("CuloareInel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("culoare_inel");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("isDeleted");

                    b.HasKey("IdInel");

                    b.ToTable("inele_prindere", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Manopere", b =>
                {
                    b.Property<int>("IdManopera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_manopera");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdManopera"));

                    b.Property<int?>("IdInelPrindere")
                        .HasColumnType("integer")
                        .HasColumnName("id_inel_prindere");

                    b.Property<int>("IdTipGalerie")
                        .HasColumnType("integer")
                        .HasColumnName("id_tip_galerie");

                    b.Property<int>("IdTipLinie")
                        .HasColumnType("integer")
                        .HasColumnName("id_tip_linie");

                    b.Property<string>("InaltimeMaxima")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("inaltime_maxima");

                    b.Property<decimal>("MaterialFolosit")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("material_folosit");

                    b.Property<string>("NumeManopera")
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("nume_manopera");

                    b.Property<decimal>("PretCurentTipGalerie")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("pret_curent_rejansa");

                    b.Property<decimal>("PretCurentTipLinie")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("pret_curent_tip_linie");

                    b.Property<string>("TipManopera")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Aleasa")
                        .HasColumnName("tip_manopera");

                    b.HasKey("IdManopera");

                    b.HasIndex("IdInelPrindere");

                    b.HasIndex("IdTipGalerie");

                    b.HasIndex("IdTipLinie");

                    b.ToTable("manopere", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Producatori", b =>
                {
                    b.Property<int>("IdProducator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_producator");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProducator"));

                    b.Property<string>("NumeProducator")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_producator");

                    b.HasKey("IdProducator");

                    b.ToTable("producatori", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", b =>
                {
                    b.Property<int>("IdProdus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_produs");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProdus"));

                    b.Property<sbyte>("ActivInMagazin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("activ_in_magazin");

                    b.Property<sbyte>("AfiseazaInNoutati")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("afiseaza_in_noutati");

                    b.Property<string>("CodProdus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar")
                        .HasColumnName("cod_produs");

                    b.Property<string>("Compozitie")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("compozitie");

                    b.Property<string>("Descriere")
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasColumnName("descriere");

                    b.Property<sbyte?>("FataReversibila")
                        .HasColumnType("tinyint")
                        .HasColumnName("fata_reversbila");

                    b.Property<int?>("IdProducator")
                        .HasColumnType("integer")
                        .HasColumnName("id_producator");

                    b.Property<string>("Ingrijire")
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasColumnName("ingrijire");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("isDeleted");

                    b.Property<string>("NumeProdus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_produs");

                    b.Property<decimal>("PretDeBaza")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("pret_baza");

                    b.Property<decimal>("PretDeBazaRedus")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("pret_baza_redus");

                    b.Property<sbyte>("ProdusLimitat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("produs_limitat");

                    b.Property<ushort?>("Stoc")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("stoc");

                    b.Property<string>("TipulProdusului")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("tip_produs");

                    b.Property<byte>("Tva")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("TVA");

                    b.HasKey("IdProdus");

                    b.HasIndex("CodProdus")
                        .IsUnique()
                        .HasDatabaseName("Index_CodProdus");

                    b.HasIndex("IdProducator");

                    b.ToTable("produse", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.ProduseCuCulori", b =>
                {
                    b.Property<int>("IdProdusCuCuloare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_produs_culoare");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProdusCuCuloare"));

                    b.Property<int>("IdCuloare")
                        .HasColumnType("integer")
                        .HasColumnName("id_culoare");

                    b.Property<int>("IdProdus")
                        .HasColumnType("integer")
                        .HasColumnName("id_produs");

                    b.HasKey("IdProdusCuCuloare");

                    b.HasIndex("IdCuloare");

                    b.HasIndex("IdProdus");

                    b.ToTable("culori_produse", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.ProduseCuDimensiuni", b =>
                {
                    b.Property<int>("IdProdusCuDimensiune")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_produs_cu_dimensiune");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProdusCuDimensiune"));

                    b.Property<int?>("IdDimensiune")
                        .HasColumnType("integer")
                        .HasColumnName("id_dimensiune");

                    b.Property<int>("IdProdus")
                        .HasColumnType("integer")
                        .HasColumnName("id_produs");

                    b.Property<decimal>("Pret")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("pret");

                    b.Property<decimal>("PretRedus")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasDefaultValue(0m)
                        .HasColumnName("pret_redus");

                    b.HasKey("IdProdusCuDimensiune");

                    b.HasIndex("IdDimensiune");

                    b.HasIndex("IdProdus");

                    b.ToTable("dimensiuni_produse", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Seturi", b =>
                {
                    b.Property<int>("IdSet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_set");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSet"));

                    b.Property<string>("DescriereSet")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasColumnName("descriere_set");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("isDeleted");

                    b.Property<string>("NumeSet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_set");

                    b.Property<decimal>("PretRedusSet")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("pret_set_redus");

                    b.Property<decimal>("PretSet")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("pret_set");

                    b.Property<sbyte>("SetActivInMagazin")
                        .HasColumnType("tinyint")
                        .HasColumnName("set_activ");

                    b.HasKey("IdSet");

                    b.ToTable("seturi", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriGalerie", b =>
                {
                    b.Property<int>("IdTipGalerie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_tip_galerie");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipGalerie"));

                    b.Property<string>("CaleRelativa")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("cale_relativa");

                    b.Property<decimal>("IncretireRejansa")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("incretire");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("isDeleted");

                    b.Property<string>("NumeTipGalerie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_galerie");

                    b.Property<decimal>("PretTipGalerie")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("pret_metru_galerie");

                    b.Property<sbyte>("SePrindeCuInele")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("prindere_inele");

                    b.HasKey("IdTipGalerie");

                    b.ToTable("tipuri_galerie", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriLinie", b =>
                {
                    b.Property<int>("IdTipLinie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_tip_linie");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipLinie"));

                    b.Property<string>("CaleRelativa")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("cale_relativa");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("isDeleted");

                    b.Property<string>("NumeTipLinie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_tip_linie");

                    b.Property<decimal>("PretPeTipLinie")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("pret_metru_linie");

                    b.HasKey("IdTipLinie");

                    b.ToTable("tipuri_linie", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriPeProduse", b =>
                {
                    b.Property<int>("IdTipPeProdus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_tip_pe_produs");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipPeProdus"));

                    b.Property<int>("IdProdus")
                        .HasColumnType("integer")
                        .HasColumnName("id_produs");

                    b.Property<int>("IdTipProdus")
                        .HasColumnType("integer")
                        .HasColumnName("id_tip_produs");

                    b.HasKey("IdTipPeProdus");

                    b.HasIndex("IdProdus");

                    b.HasIndex("IdTipProdus");

                    b.ToTable("tipuri_pe_produse", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriProduse", b =>
                {
                    b.Property<int>("IdTipProdus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_tip_pe_produs");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipProdus"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar")
                        .HasColumnName("categorie");

                    b.HasKey("IdTipProdus");

                    b.ToTable("tipuri_produse", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductVouchersModels.Vouchere", b =>
                {
                    b.Property<int>("IdVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_voucher");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVoucher"));

                    b.Property<string>("CodVoucher")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("cod_voucher");

                    b.Property<DateTime>("DataExpirare")
                        .HasColumnType("date")
                        .HasColumnName("data_expirare");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("isDeleted");

                    b.Property<decimal>("Reducere")
                        .HasPrecision(2, 2)
                        .HasColumnType("decimal(2,2)")
                        .HasColumnName("reducere");

                    b.HasKey("IdVoucher");

                    b.ToTable("vouchere", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.Adrese", b =>
                {
                    b.Property<int>("IdAdresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_adresa");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAdresa"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("alias");

                    b.Property<string>("Bloc")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("bloc");

                    b.Property<int>("IdCont")
                        .HasColumnType("integer")
                        .HasColumnName("id_cont");

                    b.Property<int?>("IdDetaliuFactura")
                        .HasColumnType("integer")
                        .HasColumnName("id_detaliu_factura");

                    b.Property<int>("IdLocatie")
                        .HasColumnType("integer")
                        .HasColumnName("id_locatie");

                    b.Property<sbyte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("isDeleted");

                    b.Property<string>("NrBloc")
                        .HasMaxLength(7)
                        .HasColumnType("varchar")
                        .HasColumnName("nr_bloc");

                    b.Property<string>("NrStrada")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar")
                        .HasColumnName("nr_strada");

                    b.Property<string>("Strada")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("strada");

                    b.Property<string>("TipAdresa")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tip_adresa");

                    b.HasKey("IdAdresa");

                    b.HasIndex("IdCont");

                    b.HasIndex("IdDetaliuFactura");

                    b.HasIndex("IdLocatie");

                    b.ToTable("adrese", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.Conturi", b =>
                {
                    b.Property<int>("IdCont")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_cont");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCont"));

                    b.Property<string>("CodActivare")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("cod_activare");

                    b.Property<DateTime?>("DataCreare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("data_creare")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<sbyte?>("Gen")
                        .HasColumnType("tinyint")
                        .HasColumnName("gen");

                    b.Property<sbyte>("IsGuest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("guest");

                    b.Property<string>("NrTelefon")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("nr_telefon");

                    b.Property<string>("Nume")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("nume");

                    b.Property<DateTime>("OraLinkConfirmare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ora_link")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasColumnName("parola");

                    b.Property<string>("Prenume")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("prenume");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("username");

                    b.Property<sbyte>("Verificat")
                        .HasColumnType("tinyint")
                        .HasColumnName("verificat");

                    b.HasKey("IdCont");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("INDEX_EMAIL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("INDEX_USERNAME");

                    b.ToTable("conturi", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.DetaliiFactura", b =>
                {
                    b.Property<int>("IdDetaliu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_detaliu");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetaliu"));

                    b.Property<string>("Cif")
                        .HasMaxLength(12)
                        .HasColumnType("varchar")
                        .HasColumnName("CIF");

                    b.Property<string>("NumeFirma")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("nume_firma");

                    b.HasKey("IdDetaliu");

                    b.ToTable("detalii_factura", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.RememberUser", b =>
                {
                    b.Property<int>("IdSesiune")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_sesiune");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSesiune"));

                    b.Property<DateTime>("ExpiresAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at")
                        .HasDefaultValueSql("(NOW() + INTERVAL 30 DAY)");

                    b.Property<int>("IdCont")
                        .HasColumnType("integer")
                        .HasColumnName("id_cont");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("sesiune_stocata");

                    b.HasKey("IdSesiune");

                    b.HasIndex("IdCont")
                        .IsUnique();

                    b.ToTable("sesiuni", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.Reviews", b =>
                {
                    b.Property<int>("IdRecenzie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_review");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRecenzie"));

                    b.Property<int>("IdCont")
                        .HasColumnType("integer")
                        .HasColumnName("id_cont");

                    b.Property<int?>("IdProdus")
                        .HasColumnType("integer")
                        .HasColumnName("id_produs");

                    b.Property<int?>("IdSet")
                        .HasColumnType("integer")
                        .HasColumnName("id_set");

                    b.Property<int>("NumarStele")
                        .HasColumnType("integer")
                        .HasColumnName("numar_stele");

                    b.Property<string>("TextRecenzie")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasColumnName("text_recenzie");

                    b.HasKey("IdRecenzie");

                    b.HasIndex("IdCont");

                    b.HasIndex("IdProdus");

                    b.HasIndex("IdSet");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.OrderRelatedModels.Comenzi", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.UserRelatedModels.Adrese", "CAdresaFacturare")
                        .WithMany("AdreseFacturarePeComanda")
                        .HasForeignKey("IdAdresaFacturare")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Adresa_Facturare");

                    b.HasOne("E_Commerce_BackEnd.Models.UserRelatedModels.Adrese", "CAdresaLivrare")
                        .WithMany("AdreseLivrarePeComanda")
                        .HasForeignKey("IdAdresaLivrare")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Adresa_Livrare");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductVouchersModels.Vouchere", "VoucherPeComanda")
                        .WithMany("VVoucherePeComenzi")
                        .HasForeignKey("IdVoucher")
                        .HasConstraintName("FK_Voucher_Comanda");

                    b.Navigation("CAdresaFacturare");

                    b.Navigation("CAdresaLivrare");

                    b.Navigation("VoucherPeComanda");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.OrderRelatedModels.ProduseCuComenzi", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.OrderRelatedModels.Comenzi", "Comanda")
                        .WithMany("PcComenzi")
                        .HasForeignKey("IdComanda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Comenzi_PC");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Culori", "PcCuloare")
                        .WithMany("CProduseCuComenzi")
                        .HasForeignKey("IdCuloare")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Culoare_ProduseComenzoi");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Dimensiuni", "PcDimensiune")
                        .WithMany("DProduseCuComenzi")
                        .HasForeignKey("IdDimensiune")
                        .HasConstraintName("FK_Dimensiune_ProduseComenzi");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Manopere", "PcManopera")
                        .WithMany("ManopereCuComenzi")
                        .HasForeignKey("IdManopera")
                        .HasConstraintName("FK_Manopera_ProduseComenzi");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", "Produs")
                        .WithMany("ComenziProduse")
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Produse_PC");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Seturi", "Set")
                        .WithMany("CombinatieSetPeComanda")
                        .HasForeignKey("IdSet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Produse_Set");

                    b.Navigation("Comanda");

                    b.Navigation("PcCuloare");

                    b.Navigation("PcDimensiune");

                    b.Navigation("PcManopera");

                    b.Navigation("Produs");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.AsociereSeturi", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Culori", "AsCuloare")
                        .WithMany("CAsociereSeturi")
                        .HasForeignKey("IdCuloare")
                        .HasConstraintName("FK_Culoare_AsociereSeturi");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Dimensiuni", "AsDimensiune")
                        .WithMany("DAsociereSeturi")
                        .HasForeignKey("IdDimensiune")
                        .HasConstraintName("FK_Dimensiune_AsociereSeturi");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Manopere", "Manopera")
                        .WithMany("ManopereStandardPeSet")
                        .HasForeignKey("IdManopera")
                        .HasConstraintName("FK_Manopera_AsociereSeturi");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", "Produs")
                        .WithMany("PAsociereSeturi")
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Produse_AS");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Seturi", "Set")
                        .WithMany("SAsociereSeturi")
                        .HasForeignKey("IdSet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Seturi_AS");

                    b.Navigation("AsCuloare");

                    b.Navigation("AsDimensiune");

                    b.Navigation("Manopera");

                    b.Navigation("Produs");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.CosCumparaturi", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.UserRelatedModels.Conturi", "Cont")
                        .WithMany("ProduseInCosPeCont")
                        .HasForeignKey("IdCont")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Culori", "Culoare")
                        .WithMany("CuloriPeCosCumparaturi")
                        .HasForeignKey("IdCuloare")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Dimensiuni", "Dimensiune")
                        .WithMany("DPeCosCumparaturi")
                        .HasForeignKey("IdDimensiune");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Manopere", "Manopera")
                        .WithMany("ManoperePeCos")
                        .HasForeignKey("IdManopera");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", "Produs")
                        .WithMany("ProduseInCos")
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Seturi", "Set")
                        .WithMany("SeturiPeCos")
                        .HasForeignKey("IdSet");

                    b.Navigation("Cont");

                    b.Navigation("Culoare");

                    b.Navigation("Dimensiune");

                    b.Navigation("Manopera");

                    b.Navigation("Produs");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Culori", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.CodCulori", "CodCuloare")
                        .WithMany("CoduriCulori")
                        .HasForeignKey("IdCodCuloare")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CodCulori");

                    b.Navigation("CodCuloare");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Imagini", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.ProduseCuCulori", "ProdusCuCuloare")
                        .WithMany("ImagProduseCuCulori")
                        .HasForeignKey("IdProdusCuCuloare")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProduseCuCuloare_Imagini");

                    b.Navigation("ProdusCuCuloare");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Manopere", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.InelePrindere", "InelPrindereLaManopera")
                        .WithMany("InelPeManopere")
                        .HasForeignKey("IdInelPrindere")
                        .HasConstraintName("FK_Inele_Prindere");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriGalerie", "TipGalerieLaManopera")
                        .WithMany("TipGalerieManopere")
                        .HasForeignKey("IdTipGalerie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tip_Galerie");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriLinie", "TipLinieLaManopera")
                        .WithMany("TipLiniePeManopere")
                        .HasForeignKey("IdTipLinie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tip_Linie");

                    b.Navigation("InelPrindereLaManopera");

                    b.Navigation("TipGalerieLaManopera");

                    b.Navigation("TipLinieLaManopera");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Producatori", "Producator")
                        .WithMany("ProducatoriProduse")
                        .HasForeignKey("IdProducator")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Producatori");

                    b.Navigation("Producator");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.ProduseCuCulori", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Culori", "Culoare")
                        .WithMany("CProduseCuCulori")
                        .HasForeignKey("IdCuloare")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Culori_ProduseCuCulori");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", "Produse")
                        .WithMany("PProduseCuCulori")
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Produse_ProduseCuCulori");

                    b.Navigation("Culoare");

                    b.Navigation("Produse");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.ProduseCuDimensiuni", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Dimensiuni", "PdDimensiune")
                        .WithMany("DProduseCuDimensiuni")
                        .HasForeignKey("IdDimensiune")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Dimensiuni_PD");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", "PdProduse")
                        .WithMany("PProduseCuDimensiuni")
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Produse_PD");

                    b.Navigation("PdDimensiune");

                    b.Navigation("PdProduse");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriPeProduse", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", "TppProdus")
                        .WithMany("PTipuriPeProduse")
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Produse_TPP");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriProduse", "TppTipProdus")
                        .WithMany("TpTipuriPeProduse")
                        .HasForeignKey("IdTipProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TipProduse_TPP");

                    b.Navigation("TppProdus");

                    b.Navigation("TppTipProdus");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.Adrese", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.UserRelatedModels.Conturi", "Cont")
                        .WithMany("AdreseConturi")
                        .HasForeignKey("IdCont")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Conturi");

                    b.HasOne("E_Commerce_BackEnd.Models.UserRelatedModels.DetaliiFactura", "DetaliuFactura")
                        .WithMany("DfAdrese")
                        .HasForeignKey("IdDetaliuFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_DetaliiFactura_Adresa");

                    b.HasOne("E_Commerce_BackEnd.Models.OrderRelatedModels.Locatii", "Locatie")
                        .WithMany("AdreseLocatii")
                        .HasForeignKey("IdLocatie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Locatii");

                    b.Navigation("Cont");

                    b.Navigation("DetaliuFactura");

                    b.Navigation("Locatie");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.RememberUser", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.UserRelatedModels.Conturi", "CurrentUserSession")
                        .WithOne("RememberUserSession")
                        .HasForeignKey("E_Commerce_BackEnd.Models.UserRelatedModels.RememberUser", "IdCont")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentUserSession");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.Reviews", b =>
                {
                    b.HasOne("E_Commerce_BackEnd.Models.UserRelatedModels.Conturi", "Cont")
                        .WithMany("ReviewsProduse")
                        .HasForeignKey("IdCont")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", "Produs")
                        .WithMany("ProductReviews")
                        .HasForeignKey("IdProdus");

                    b.HasOne("E_Commerce_BackEnd.Models.ProductRelatedModels.Seturi", "Set")
                        .WithMany("ReviewPeSet")
                        .HasForeignKey("IdSet");

                    b.Navigation("Cont");

                    b.Navigation("Produs");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.OrderRelatedModels.Comenzi", b =>
                {
                    b.Navigation("PcComenzi");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.OrderRelatedModels.Locatii", b =>
                {
                    b.Navigation("AdreseLocatii");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.CodCulori", b =>
                {
                    b.Navigation("CoduriCulori");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Culori", b =>
                {
                    b.Navigation("CAsociereSeturi");

                    b.Navigation("CProduseCuComenzi");

                    b.Navigation("CProduseCuCulori");

                    b.Navigation("CuloriPeCosCumparaturi");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Dimensiuni", b =>
                {
                    b.Navigation("DAsociereSeturi");

                    b.Navigation("DPeCosCumparaturi");

                    b.Navigation("DProduseCuComenzi");

                    b.Navigation("DProduseCuDimensiuni");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.InelePrindere", b =>
                {
                    b.Navigation("InelPeManopere");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Manopere", b =>
                {
                    b.Navigation("ManopereCuComenzi");

                    b.Navigation("ManoperePeCos");

                    b.Navigation("ManopereStandardPeSet");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Producatori", b =>
                {
                    b.Navigation("ProducatoriProduse");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Produse", b =>
                {
                    b.Navigation("ComenziProduse");

                    b.Navigation("PAsociereSeturi");

                    b.Navigation("PProduseCuCulori");

                    b.Navigation("PProduseCuDimensiuni");

                    b.Navigation("PTipuriPeProduse");

                    b.Navigation("ProductReviews");

                    b.Navigation("ProduseInCos");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.ProduseCuCulori", b =>
                {
                    b.Navigation("ImagProduseCuCulori");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.Seturi", b =>
                {
                    b.Navigation("CombinatieSetPeComanda");

                    b.Navigation("ReviewPeSet");

                    b.Navigation("SAsociereSeturi");

                    b.Navigation("SeturiPeCos");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriGalerie", b =>
                {
                    b.Navigation("TipGalerieManopere");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriLinie", b =>
                {
                    b.Navigation("TipLiniePeManopere");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductRelatedModels.TipuriProduse", b =>
                {
                    b.Navigation("TpTipuriPeProduse");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.ProductVouchersModels.Vouchere", b =>
                {
                    b.Navigation("VVoucherePeComenzi");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.Adrese", b =>
                {
                    b.Navigation("AdreseFacturarePeComanda");

                    b.Navigation("AdreseLivrarePeComanda");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.Conturi", b =>
                {
                    b.Navigation("AdreseConturi");

                    b.Navigation("ProduseInCosPeCont");

                    b.Navigation("RememberUserSession");

                    b.Navigation("ReviewsProduse");
                });

            modelBuilder.Entity("E_Commerce_BackEnd.Models.UserRelatedModels.DetaliiFactura", b =>
                {
                    b.Navigation("DfAdrese");
                });
#pragma warning restore 612, 618
        }
    }
}
